# Generated by Django 3.2.9 on 2021-12-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_remove_nodocente_full_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodocente',
            old_name='NOficina',
            new_name='oficina',
        ),
    ]
